// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Mode } from "./Mode";
import type { PodId } from "./PodId";

export type RemoveRequest = { pod: PodId, mode: Mode, };
