// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiskSizeInfo = { free_size: number, total_size: number, files: bigint, ffree: bigint, bsize: number, };
