// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigType } from "./ConfigType";

export type GenerateConfigAnswer = "Success" | "SuccessDefault" | "PodNotFound" | "NotADirectory" | { "WriteFailed": [string, ConfigType] } | { "CantOverwrite": ConfigType } | "ConfigBlock";
