// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IoError } from "./IoError";

export type GetHostsAnswer = { "Hosts": Array<string> } | "FileNotInsideARunningPod" | "FileNotFound" | { "WrongFileType": string } | { "FailedToGetHosts": IoError };
