// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PeerInfo } from "./PeerInfo";

export type InspectInfo = { url: string | null, hostname: string, name: string, connected_peers: Array<PeerInfo>, mount: string, };
