// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskSizeInfo } from "./DiskSizeInfo";
import type { PeerInfo } from "./PeerInfo";

export type InspectInfo = { public_url: string | null, bound_socket: string, hostname: string, name: string, connected_peers: Array<PeerInfo>, mount: string, disk_space: DiskSizeInfo | null, };
