// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { IoError } from "./IoError";

export type NewAnswer = { "Success": string } | "AlreadyExist" | "AlreadyMounted" | "InvalidIp" | "InvalidUrlIp" | { "ConflictWithConfig": string } | { "BindImpossible": IoError } | { "FailedToCreatePod": IoError };
