// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewRequest = { name: string, port: number | null, mountpoint: string, url: string | null, hostname: string | null, listen_url: string | null, additional_hosts: Array<string>, };
