// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewRequest = { name: string, mountpoint: string, url: string | null, public_url: string | null, ip_address: string | null, port: number | null, hostname: string | null, additional_hosts: Array<string>, };
