// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShowConfigAnswer = { "SuccessBoth": [string, string] } | { "SuccessLocal": string } | { "SuccessGlobal": string } | "PodNotFound" | "ConfigBlock";
