// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatsPerFiletypeAnswer = { "Stats": { [key in string]?: number } } | "PodNotFound" | "InternalError";
