// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CliHostTree } from "./CliHostTree";
import type { IoError } from "./IoError";

export type TreeAnswer = { "Tree": CliHostTree } | "PodNotFound" | { "PodTreeFailed": IoError };
